### ISSUE TITLE
You may want to reupload smoothbedrock-1.1.3.jar to curseforge

### ISSUE THREAD

**Issue by calloatti** [Blayyke/SmoothBedrockFabric#1]
For some reason the curseforge api for the file smoothbedrock-1.1.3.jar is missing data:

https://addons-ecs.forgesvc.net/api/v2/addon/311280/file/2705720

Compare it to smoothbedrock-1.0.jar

https://addons-ecs.forgesvc.net/api/v2/addon/311280/file/2659619

smoothbedrock-1.1.3.jar has no MC version data and has no "modules" data.

This missing data breaks updaters that rely on the curseforge api.

**Comment by Blayyke** [comment]
I've just uploaded a new version but it seems that the modules array is still empty. Not sure what I can do on my end for this. The jars do definitely have the files that the 1.0 modules data references still though.
