### ISSUE TITLE
No nether roof on 1.16.1

### ISSUE THREAD

**Issue by ghost** [Blayyke/SmoothBedrockFabric#2]
In 1.16.1 the nether roof isn't generated while this mod is loaded.

![image](https://user-images.githubusercontent.com/918422/87493717-b7674000-c64d-11ea-9329-c746cfb0b958.png)

My config:
```
{
	// true: Dimensions in filter will have flat bedrock. false: Dimensions in list will not have flat bedrock
	"isWhitelist": false,
	// A list of dimension ids that this mod should filter based on the 'Act as whitelist' setting.
	"dimensionFilter": [
		"minecraft:the_end"
	]
}
```

**Comment by ghost** [comment]
Thank you for the fix!

**Comment by Blayyke** [comment]
Forgot to reply but fixed in https://github.com/Blayyke/SmoothBedrockFabric/commit/45c250f675a6920d6cc6b7a6a749dc2d02a4793a
